language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-hirsch' ]; then cd .. && eval "mv $currentfolder generator-hirsch" && cd generator-hirsch; fi
